[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/tokyonight/tokyonight_night.toml"]
#import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 5
y = 5

[font]
size = 8.0

normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Medium Italic"

#[font.normal]
#family = "FiraCode Nerd Font Mono"
#style = "Medium"
